### ISSUE TITLE
Feedback on "Switch to Dark Theme" Feature Draft

### ISSUE THREAD

**Issue by AlejandraPerry** [AlejandraPerry/intro-to-python-noble-vikings#14]
Hello @jose-unanue ,

The adjustments you've made to the UI look good! I appreciate how you have also corrected parts of syntax and removed unnecessary code. However, sometimes the time formatting looks a little awkward when printing "0 m" or "0 s" like in the example below:

![image](https://github.com/user-attachments/assets/c5b3745c-a1be-4b34-adb6-909a32d7c218)

A way to adjust this formatting is by changing "0m 43s" formatting to "00:43", which is a more common way of displaying song duration. After changing the time values to strings, I adjusted the minute and seconds to always have two digits with the padStart function and separated them with a colon instead of a space.

![image](https://github.com/user-attachments/assets/d5924eac-62b2-4afb-b2cd-9499dd032b2d)

Additionally, we should also consider themes other than light and dark through the user's choices in colors and fonts. This would make the UI appear more personalized. In other words, we could generate two functional features (Light/Dark Mode and Themes Options) out of these types of changes to HTML code.

Please let me know what you think!

Thank you,

Alejandra

**Comment by jose-unanue** [comment]
Sounds good. It will take me some time to implement the themes feature because I need to make everything reusable for the other features to work with this properly.

Thank you for the feedback.
