### ISSUE TITLE
Feature 3: Favorite Option

### ISSUE THREAD

**Issue by kevinrest95** [AlejandraPerry/intro-to-python-noble-vikings#3]
This Python program allows users to manage a playlist by adding songs, marking their favorite songs with a heart option, and filtering the playlist to show only the favorite songs.

Features:
Add Songs: Users can add songs to a playlist.

Heart Songs: Users can mark their favorite songs with a heart.

Filter Favorites: Users can filter the playlist to show only their favorite songs.

**Comment by kevinrest95** [comment]
I can also work on this

**Comment by AlejandraPerry** [comment]
I cannot see the revisions you made. Please open a new pull request with your revisions. Additionally, please be more descriptive in your commit messages.

Thank you!

**Comment by kevinrest95** [comment]
Its already merged into the main repository. Its a grey heart that appears next to the title track name that turns red when clicked. 

Please see the following lines in the Index file: 

32-49
259-286
290-295
299
307
318-344

Thank you
