### ISSUE TITLE
Feature 4: 1- 5 Star Ranking

### ISSUE THREAD

**Issue by kevinrest95** [AlejandraPerry/intro-to-python-noble-vikings#4]
This Python program enhancement allows users to rank songs on a scale from 1 to 5. Each song can be rated by filling in stars, where grey stars represent unfilled ratings and gold stars represent filled ratings.

Features:

Rate Songs- Users can rate each song from 1 to 5 stars.
Display Ratings and Update When Clicked Anew.

Opens possibility for algorithmic playlist creation according to the users presences should the application be further developed into a more complex prototype.

**Comment by kevinrest95** [comment]
Added this feature, accidentally did so under the title of "added queue button," not sure how to correct that. No longer pursuing the addition of the queue button feature due to breaking of the code in previous attempts.

**Comment by AlejandraPerry** [comment]
Could you open a pull request to merge this feature? Thank you,
